#!/usr/bin/env python

import pandas as pd
import matplotlib.pyplot as plt
metadata = pd.read_csv("~/qbb2015/rawdata/samples.csv")
metadata1 = pd.read_csv("~/qbb2015/rawdata/replicates.csv")


Sxl = []
Sxl2=[]
Sxl3=[]
Sxl4=[]
stage=[]

for sample in metadata[metadata["sex"] == "female"]["sample"]:
    df= pd.read_table("~/qbb2015/stringtie/" + sample + "/t_data.ctab")
    roi = df["t_name"].str.contains("FBtr0331261")
    Sxl.append(df[roi]["FPKM"].values)
    
for sample in metadata[metadata["sex"] == "male"]["sample"]:
    df= pd.read_table("~/qbb2015/stringtie/" + sample + "/t_data.ctab")
    roi2 = df["t_name"].str.contains("FBtr0331261")
    Sxl2.append(df[roi2]["FPKM"].values)
    
for sample in metadata1[metadata1["sex"]=="male"]["sample"]:
    df= pd.read_table("~/qbb2015/stringtie/" + sample + "/t_data.ctab")
    roi2 = df["t_name"].str.contains("FBtr0331261")
    Sxl3.append(df[roi2]["FPKM"].values)

for sample in metadata1[metadata1["sex"]=="female"]["sample"]:
    df= pd.read_table("~/qbb2015/stringtie/" + sample + "/t_data.ctab")
    roi2 = df["t_name"].str.contains("FBtr0331261")
    Sxl4.append(df[roi2]["FPKM"].values)


for x in metadata["stage"][0:8]:
    stage.append(x)
    
plt.figure()
plt.plot(Sxl, "-b",label="female")
plt.plot(Sxl2, "-r",label= "male")
plt.plot([4,5,6,7], Sxl3,"ro")
plt.plot([4,5,6,7], Sxl4,"bo")
plt.legend(bbox_to_anchor=(0.5, 1))
plt.title("Sxl")
plt.xticks(range(8), stage, rotation=90)
plt.xlabel("Developmental Storage")
plt.ylabel("m-RNA abundance (FPKM)")
plt.savefig("timecourse.png")