#!/usr/bin/env python

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

filename = "/Users/cmdb/qbb2015/stringtie/SRR072893/t_data.ctab"

df = pd.read_table("~/qbb2015/stringtie/SRR072893/t_data.ctab")
FPKM = {}

ROI = df["FPKM"] > 0
print df["FPKM"][ROI]
df1= df["FPKM"][ROI]
for i in df:
    if ROI is true:
        FPKM{} += 1
     else:
        FPKM{} +=0
print FPKM


plt.figure()
plt.hist((x, bins=10, range=None, normed=False, weights=None, cumulative=False, bottom=None, histtype=u'bar', align=u'mid', orientation=u'vertical', rwidth=None, log=False, color=None, label=None, stacked=False, hold=None, **kwargs)
plt.title("Histogram")
plt.xlabel("?")
plt.ylabel("?")
plt.savefig("Histogram.png")