#!/usr/bin/env python

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

filename = "/Users/cmdb/qbb2015/stringtie/SRR072893/t_data.ctab"

df = pd.read_table("~/qbb2015/stringtie/SRR072893/t_data.ctab")
"""FPKM = {}

ROI = df["FPKM"]

for i in df:
    if ROI is true:
         += 1
     else:
        FPKM{} +=0
print FPKM"""
roi = df["FPKM"]
roi2 = roi[roi > 0]
roi3 = np.log(roi2.values)
plt.figure()
plt.hist(roi3)
plt.title("Histogram")
plt.xlabel("log(FPKM)")
plt.ylabel("Count")
plt.savefig("Histogram.png")